App.User = DS.Model.extend( App.savingMixin, {
	url: DS.attr('string'),
	username: DS.attr('string'),
	email: DS.attr('string'),
	is_staff: DS.attr('boolean'),
	password: DS.attr('string'),
	last_login: DS.attr('date'),
	is_superuser: DS.attr('boolean'),
	slug: DS.attr('string'),
	location: DS.attr('string'),
	last_seen: DS.attr('date'),
	last_ip: DS.attr('string'),
	timezone: DS.attr('string'),
	is_administrator: DS.attr('boolean'),
	is_moderator: DS.attr('boolean'),
	topic_count: DS.attr('number'),
	comment_count: DS.attr('number'),
	first_name: DS.attr('string'),
	last_name: DS.attr('string'),
	is_active: DS.attr('boolean'),
	date_joined: DS.attr('date'),
	avatar: DS.attr('string'),
	groups: DS.attr('string'),
	user_permissions: DS.attr('string')
});