Ember.TEMPLATES["environment"] = Ember.Handlebars.template({"1":function(depth0,helpers,partials,data) {
  var helperMissing=helpers.helperMissing, escapeExpression=this.escapeExpression, buffer = '';
  data.buffer.push("			");
  data.buffer.push(escapeExpression(((helpers.render || (depth0 && depth0.render) || helperMissing).call(depth0, "obstacleLocation", "obs", {"name":"render","hash":{},"hashTypes":{},"hashContexts":{},"types":["STRING","ID"],"contexts":[depth0,depth0],"data":data}))));
  data.buffer.push("\r\n");
  return buffer;
},"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
  var stack1, escapeExpression=this.escapeExpression, helperMissing=helpers.helperMissing, buffer = '';
  data.buffer.push("<div class=\"row\">\r\n	<div class=\"col-sm-12\">\r\n		<div class=\"hcontrols row\">\r\n			<div class=\"col-sm-8\">\r\n			</div>\r\n			<div class=\"col-sm-4\">\r\n				<button ");
  data.buffer.push(escapeExpression(helpers.action.call(depth0, "gotoExperiment", {"name":"action","hash":{},"hashTypes":{},"hashContexts":{},"types":["STRING"],"contexts":[depth0],"data":data})));
  data.buffer.push(" class=\"btn btn-turquesa\" style=\"margin: 5px\">Go to Experiment</button>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>\r\n<div class=\"row\">\r\n	<div class=\"col-sm-12\">\r\n		<div class=\"whitefont\">Ambient Temperature</div>\r\n	</div>\r\n</div>\r\n<div class=\"row\">\r\n    <div class=\"col-sm-12 block\">\r\n        <div>\r\n            <input id=\"environmentTempSlider\" class='simpleSlider' data-slider-id='environmentTempSlider' type=\"text\" data-slider-min=\"0\" data-slider-max=\"100\" data-slider-step=\"0.1\" data-slider-value=\"14\"/>     \r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=\"panel-group\" id=\"accordion\" role=\"tablist\" aria-multiselectable=\"true\">\r\n  <div class=\"\">\r\n    <div class=\"title\" role=\"tab\" id=\"headingFour\">\r\n      <h4 class=\"panel-title smallmargin\">\r\n        <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseOne\" aria-expanded=\"false\" aria-controls=\"collapseOne\">\r\n          Worm Status\r\n        </a>\r\n      </h4>\r\n    </div>\r\n    <div id=\"collapseOne\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingFour\">\r\n      <div class=\"panel-body\">\r\n        ");
  data.buffer.push(escapeExpression(((helpers.render || (depth0 && depth0.render) || helperMissing).call(depth0, "wormStatus", "wormStatus", {"name":"render","hash":{},"hashTypes":{},"hashContexts":{},"types":["STRING","ID"],"contexts":[depth0,depth0],"data":data}))));
  data.buffer.push("\r\n      </div>\r\n    </div>\r\n  </div>\r\n  <div class=\"\">\r\n    <div class=\"title\" role=\"tab\" id=\"headingOne\">\r\n      <h4 class=\"panel-title smallmargin\">\r\n        <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseFour\" aria-expanded=\"false\" aria-controls=\"collapseFour\">\r\n          Plate Configuration\r\n        </a>\r\n      </h4>\r\n    </div>\r\n    <div id=\"collapseFour\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingOne\">\r\n      <div class=\"panel-body\">\r\n        ");
  data.buffer.push(escapeExpression(((helpers.render || (depth0 && depth0.render) || helperMissing).call(depth0, "plateConfiguration", "plateConfiguration", {"name":"render","hash":{},"hashTypes":{},"hashContexts":{},"types":["STRING","ID"],"contexts":[depth0,depth0],"data":data}))));
  data.buffer.push("\r\n      </div>\r\n    </div>\r\n  </div>\r\n  <div class=\"\">\r\n    <div class=\"title\" role=\"tab\" id=\"headingThree\">\r\n      <h4 class=\"panel-title smallmargin\">\r\n        <a class=\"collapsed\" role=\"button\" data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n          Obstacles\r\n        </a>\r\n      </h4>\r\n    </div>\r\n    <div id=\"collapseThree\" class=\"panel-collapse collapse\" role=\"tabpanel\" aria-labelledby=\"headingThree\">\r\n      <div class=\"panel-body\">\r\n		<div class=\"row\">\r\n			<div class=\"col-sm-8\">\r\n				<button class=\"btn btn-turquesa\" data-toggle=\"modal\" data-target=\"#newModalObstacle\">New Obstacle</button>\r\n			</div>\r\n		</div>					\r\n");
  stack1 = helpers.each.call(depth0, "obs", "in", "obstacle", {"name":"each","hash":{},"hashTypes":{},"hashContexts":{},"fn":this.program(1, data),"inverse":this.noop,"types":["ID","ID","ID"],"contexts":[depth0,depth0,depth0],"data":data});
  if (stack1 != null) { data.buffer.push(stack1); }
  data.buffer.push("      </div>\r\n    </div>\r\n  </div>\r\n</div>\r\n\r\n\r\n\r\n<div class=\"modal fade\" id=\"newModalObstacle\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">\r\n	<div class=\"modal-dialog\" role=\"document\">\r\n		<div class=\"modal-content color\">\r\n			<div class=\"modal-header\">\r\n				<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n				<h4 class=\"modal-title\" id=\"myModalLabel\">New Obstacle</h4>\r\n			</div>\r\n			<div class=\"row\">\r\n				<div class=\"col-sm-12\">\r\n					<div class=\"title centered\">Type</div>\r\n				</div>\r\n			</div>\r\n			<div class=\"row\">\r\n				<div class=\"col-sm-12 block\">\r\n					<select class=\"btn\" id=\"createObstacleType\">\r\n						<option>Cube</option>\r\n						<option>Cylinder</option>\r\n						<option>Hexagonal</option>\r\n					</select>\r\n				</div>\r\n			</div>\r\n			<div class=\"modal-footer\">\r\n				<button ");
  data.buffer.push(escapeExpression(helpers.action.call(depth0, "addObstacle", {"name":"action","hash":{},"hashTypes":{},"hashContexts":{},"types":["STRING"],"contexts":[depth0],"data":data})));
  data.buffer.push(" type=\"button\" class=\"btn btn-turquesa\" data-dismiss=\"modal\">Create</button>\r\n				<button type=\"button\" class=\"btn btn-turquesa\" data-dismiss=\"modal\">Cancel</button>\r\n			</div>\r\n		</div>\r\n	</div>\r\n</div>");
  return buffer;
},"useData":true});